language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
 
matrix:
  allow_failures:
    - php: 5.6

before_script:
  - sudo apt-get install -y -qq libssh2-1-dev libssh2-php
  - pecl install -f ssh2-beta < .noninteractive
  - php -m | grep ssh2
  - composer self-update
  - composer install --dev
